baseurl = "https://www.catherinetcai.com"
DefaultContentLanguage = "en"
title = "Cat Cai"
author = "Cat Cai"
copyright = "Copyright 2020, Cat Cai"
enableRobotsTXT = true
theme = "hugo-bearblog"
languageCode = "en-US"
metaDataFormat = "yaml"
publishDir = "public"

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  title = "Cat Cai"
  subtitle = "Adventures in software confusion"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[markup.goldmark.renderer]
  unsafe = true
